name: expensemate2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Veritabanı
  drift: ^2.13.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2

  # Grafik & görselleştirme
  fl_chart: ^0.66.0

  # Genel
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  csv: ^5.0.2
  permission_handler: ^11.1.0
  share_plus: ^7.0.2
  pdf: ^3.10.7
  file_selector: ^1.0.3
  syncfusion_flutter_pdf: ^24.2.9

  # Bildirimler
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  flutter_timezone: ^4.1.1
  # HTTP istekleri
  http: ^1.1.0
  # Dil desteği
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.13.0
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.png
    - assets/splash/splash.png
    - assets/lottie/empty.json
    - assets/lottie/success.json
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#673AB7"
  image: assets/splash/splash.png
  android: true
  ios: true
